version: "2"

services:
  postgres:
    image: supsi4faredge/openapi4virtualization:postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
  virtual-factory-layer1:
    image: supsi4faredge/openapi4virtualization:virtual-factory
    container_name: virtual-factory-layer1
    command: [sh, -c, "java -jar -Dspring.profiles.active=layer1 /virtual-factory.jar"]
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 7001:7001
  virtual-factory-layer2:
    image: supsi4faredge/openapi4virtualization:virtual-factory
    container_name: virtual-factory-layer2
    command: [sh, -c, "java -jar -Dspring.profiles.active=layer2 /virtual-factory.jar"]
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 7002:7002
